### ISSUE TITLE
not working (only pop-up)

### ISSUE THREAD

**Issue by ghost** [pchomik/linter-python#33] opened 2016-12-24 00:13 UTC
I installed the linter-python and did everything I should do.
When I modify a file and save it with an syntax error, I don't get any underlines or circles in the left or whatever, I just get a red pop-up on the upper right corner saying:
"Execution finished with error:

Error: spawn EACCES"

I don't know a lot about programming and how the computer works so I might have done something wrong.. but I'm not sure what. Can I get some help?

**Comment by AntoineLevesque** [comment] 2017-03-13 00:53
I have the same issue.

**Comment by Arcanemagus** [comment] 2017-03-13 16:36
Usually when you are getting this you have set a _directory_ in the "Executable Path" setting, instead of the full path of `pylama`.

**Comment by pchomik** [comment] 2017-03-13 20:22
I tried to reproduce your error on Ubuntu machine and I was not able to reproduce it.

Could you do few steps to show what is going on:
* Enable "debug" option in plugin settings
* Press CTRL+SHIFT+I to open development tool window
* Press CTRL+SHIFT+F5 to reload window
* Open your python file and reproduce error

After that please provide Console output. Plugin should print many information about execution.

Good luck

**Comment by pchomik** [comment] 2017-04-10 20:39
@goodmj97 @AntoineLevesque any news about this issue. Could you provide more detailds?

**Comment by pchomik** [comment] 2017-05-22 21:36
I'm closing issue because there was not response.

**Closed as completed by pchomik** 2017-05-22 21:36 UTC
